In [2]:
import openpyxl
wb = openpyxl.load_workbook('./sample.xlsx')
sheet = wb['Sheet1']
print(sheet.max_column,sheet.max_row)

3 6


In [4]:
import openpyxl
for row in sheet.iter_rows(min_row = 2):
    for cell in row:
        print(cell.value)
    print('-' * 10)
wb.close()

Kei
35
1234-1234
----------
Hong
26
4320-1420
----------
Kim
41
1234-5678
----------
Choi
38
4023-3411
----------
Go
27
1469-4023
----------


In [6]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[1,1],[1,1]])
C = A + B
print(C)

[[2 3]
 [4 5]]


### pandas는 데이터 분석 및 처리를 위한 필수 라이브러리
- 행과 열로 구성된 데이터 객체를 편리하게 관리
- 대용량 데이터를 처리하는데 용이
- 가공된 데이터를 저장하거나 저장된 파일을 불러와 데이터 객체로 만든다.

In [7]:
import pandas as pd
user_list = pd.read_excel('sample.xlsx',sheet_name = 'Sheet1')
print(user_list)

     이름  나이       전화번호
0   Kei  35  1234-1234
1  Hong  26  4320-1420
2   Kim  41  1234-5678
3  Choi  38  4023-3411
4    Go  27  1469-4023


### 토크나이징 소개
- 우리가 일상에서 사용하는 언어 = 자연어
- 컴퓨터는 자연어를 직접적으로 이해 X
- 자연어 처리 NLP
- 챗봇 엔진도 자연어 처리의 한 분야
- token의 단위는 토크나이징 방법에 따라 달라질 수 있다.
### 한국어 자연어 처리에 많이 사용하는 라이브러리
- KoNLPy

In [2]:
%pip install konlpy

   ---------------------------------------- 0.0/19.4 MB ? eta -:--:--
   --------------------- ------------------ 10.5/19.4 MB 59.4 MB/s eta 0:00:01
   ---------------------------------------  19.4/19.4 MB 61.1 MB/s eta 0:00:01
   ---------------------------------------- 19.4/19.4 MB 45.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [6]:
from konlpy.tag import Kkma

kkma = Kkma()

text = "아버지가 방에 들어갑니다."
morphs = kkma.morphs(text)
print(morphs)

JVMNotFoundException: No JVM shared library file (jvm.dll) found. Try setting up the JAVA_HOME environment variable properly.

### 4.1 임베딩이란?
- 컴퓨터는 자연어를 직접적으로 처리 불가능
- 컴퓨터는 수치 연산만 가능, 자연어를 숫자나 벡터 형태로 변환
- 자연어 처리 분야에서는 임베딩이라고 한다.

### 4.2 단어 임베딩
- 단어 임베딩은 말뭉치에서 각각의 단어를 벡터로 변환

In [2]:
%pip install -q konlpy

Note: you may need to restart the kernel to use updated packages.


In [17]:
from dotenv import load_dotenv
load_dotenv()

True

In [19]:
jvmpath = r"C:\Program Files\Eclipse Adoptium\jdk-21.0.8.9-hotspot\bin\server\jvm.dll"

In [20]:
from konlpy.tag import Komoran
komoran = Komoran(jvmpath)


In [21]:
from konlpy.tag import Komoran
import numpy as np
komoran = Komoran()
text = '오늘 날씨는 구름이 많아요.'

# 명사만 추출
nouns = komoran.nouns(text)
print(nouns)

dics = {}
for word in nouns:
    if word not in dics.keys():
        dics[word] = len(dics)
print(dics)

nb_classes = len(dics)
targets = list(dics.values())
one_hot_targets = np.eye(nb_classes)[targets]
print(one_hot_targets)

['오늘', '날씨', '구름']
{'오늘': 0, '날씨': 1, '구름': 2}
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 4.2.2 희소 표현과 분산 표현
- 앞서 소개한 원-핫 인코딩은 표현하고자 하는 단어의 인덱스 요소만 1이고 나머지 요소는 모두 0으로 표현되는 희소 벡터(또는 희소 행렬)입니다. 
- 이처럼 단어가 희소 벡터로 표현되는 방식을 희소 표현이라 부릅니다. 
## 자연어 처리를 잘하기 위해서는 기본 토큰이 되는 단어의 의미와 주변 단어 간의 관계가 단어 임배팅에 표현
- 각 단어 간의 유사성을 잘 표현하면서도 벡터 공간을 절약할 수 있는 방법을 고안
- 분산 표현이라고 한다.
- NOTE_: 이를 쉽게 하기 위해 분산 표현으로 RGB 색상을 예로 들었지만 신경망 모델에서의 분산 표현은 사람이 직관적으로 이해하기 어렵다.

### 희소 표현 방식에 비해 분산 표현 방식은 2가지 장점을 가진다.
1. 임베딩 벡터의 차원을 데이터 손실을 최소화
- 희소 표현 방식은 단어를 표현하는데 너무 많은 자원이 필요
1. 임베딩 벡터에는 단어의 의미, 주변 단어간의 관계 등 많은 정보가 내포되어 있어 일반화 능력이 뛰어나다.


### 5.1 텍스트 유사도 개요
- 자연어 처리에서 문장 간에 의미가 얼마나 유사한지 계산하는 일은 매우 중요
- 우리는 의식하진 않지만 두 개의 문장에 동일한 단어나 의미상 비슷한 단어들이 얼마나 분포되어 있는지 직감적으로 파악
- 컴퓨터도 동일한 방법으로 두 문장 간의 유사도를 계산
### FAQ에 응대하는 Q&A 챗봇 개발
- 챗봇 엔진에 입력되는 문장과 시스템에서 해당 주제의 답변과 연관된 질문이 얼마나 유사한지 게산
- 적절한 답변을 출력할 수 있다.
-> 두 문장 간의 유사도를 계산하기 위해서는 문장 내에 존재하는 단어들을 수치화해야한다.
## 통계적인 방법을 이용하여 유사도를 계산하는 방법을 살펴본다.
- 통계적인 방식이 더 적절, 개발하려는 챗봇의 주제에 따라 사용하면 챗봇 엔진 성능 향상에 도움 

## 5.2 n-gram 유사도
- n-gram은 주어진 문장에서 n개의 연속적인 단어 시퀀스를 의미한다. 
- 이는 이웃한 단어의 출현 횟수를 통계적으로 표현해 텍스트의 유사도를 계산하는 방법
- 

In [32]:
from konlpy.tag import Komoran
komoran = Komoran(jvmpath)
def word_ngram(bow, num_gram):
    text = tuple(bow)
    ngrams = [text[x:x+num_gram] for x in range(0,len(text))]
    return tuple(ngrams)
def similarity(doc1, doc2):
    cnt = 0 
    for token in doc1:
        if token in doc2:
            cnt +=1
    return cnt/len(doc1)

sentence1 = '6월에 뉴턴은 선생님의 제안으로 트리니티에 입학했다.'
sentence2 = '6월에 뉴턴은 선생님의 제안으로 대학교에 입학했다.'
sentence3 = '나는 맛있는 밥을 뉴턴 선생님과 함께 먹었다.'
bow1 = komoran.nouns(sentence1)
bow2 =komoran.nouns(sentence2)
bow3 = komoran.nouns(sentence3)
doc1 = word_ngram(bow1,2)
doc2 = word_ngram(bow2, 2)
doc3 = word_ngram(bow3, 2)
print(doc1)
print(doc2)

r1 = similarity(doc1, doc2)
r2 =similarity(doc3, doc1)
print(r1)
print(r2)

(('6월', '뉴턴'), ('뉴턴', '선생님'), ('선생님', '제안'), ('제안', '트리니티'), ('트리니티', '입학'), ('입학',))
(('6월', '뉴턴'), ('뉴턴', '선생님'), ('선생님', '제안'), ('제안', '대학교'), ('대학교', '입학'), ('입학',))
0.6666666666666666
0.0
